### ISSUE TITLE
练手示例

### ISSUE THREAD

**Issue by weihongliang233** [RubiscoP/Machine_Learning#1]
数据集长啥样？我们能拿到数据集，将计算熵以及ML的过程走一遍（先不管用哪种算法，总之走一遍流程）吗？

**Comment by RubiscoP** [comment]
现在没有数据，俞老师之前说的是开学给，我再问下。其实走流程的话，随便找一个kaggle上的简单competition就可以了，比如泰坦尼克号那个教学项目，或者房价预测那个。
